### ISSUE TITLE
Question: How sensitive is the model to molecule initialization?

### ISSUE THREAD

**Issue by jrhorne** [aspuru-guzik-group/JANUS#1]
Hello, great work! I'm excited to try this out for a chemical design project I'm working on. One question that I had after reading the pre-print— _how sensitive is the model to molecule initialization?_

I read that you can start JANUS with random molecules or provide it with defined molecules. Did you perform any tests on what happens if the best molecule's scaffold was ablated from the initial bank of molecules? And how much, if at all, does rational initialization improve over random molecular initialization? Does this relate back to being trapped in local minima, and would the choice of initialization help explore more chemical space?

Thank you!

**Comment by akshat998** [comment]
Hi @jrhorne, 
Thank you for your question!

We do not evaluate the effect of the initial population in detail. However, in general, local minima can be encountered multiple times with the same initial molecules. Hence changing the initial set across multiple runs would lead to different results.

The advantage of having an initial bank is that one sees more synthesizable molecules compared to random molecules (most random molecules are not stable/synthesizable). 

I hope this helps. Please let me know if there are any further questions :) 
Akshat
