### ISSUE TITLE
Enquiring on multi-objective fitness function

### ISSUE THREAD

**Issue by yipy0005** [aspuru-guzik-group/JANUS#10]
Hi, I would like to ask if there are multiple objectives which I want the fitness function to fulfil, how would I write out the function because the example on the README.md is only for one objective (logP)?

Thank you! :D

**Comment by gkwt** [comment]
Thanks for the question! 
 
One way to do this right now is to do a linear combination of your different objectives. But we are currently working on some more sophisticated multi-objective methods.

**Comment by akshat998** [comment]
Perhaps I can give an example that would fulfill your request @yipy0005. Suppose I wasnt logP closr to 5 , SAS (sythetic accessability as small as possible) & a QED value of 0.7. 

An appropriate fitness function might then be: 
`F = -SAS + (logP - 5)**2 + (QED - 0.7)**2
`

Hope this makes sense & please let us know if any clarifications are required :) 
Akshat

**Comment by yipy0005** [comment]
Hi all, thanks for your answers, it absolutely helped me! :D
