### ISSUE TITLE
Save all molecules from each generation

### ISSUE THREAD

**Issue by pykao** [aspuru-guzik-group/JANUS#12]
I am running the experiments for N generations but the model only gives the generated molecules of N-th generation. How can I also save the molecules from previous generation?

**Comment by akshat998** [comment]
Hi @pykao 

It should be in the RESULTS directors within the directory of each generation.

Confirming with @gkwt that this is the case. Let me know if it is not :)

Regards
Akshat

**Comment by pykao** [comment]
unfortunately, it is not the case. it only store the results from the last generation.

**Comment by akshat998** [comment]
Hi @pykao, 

It's actually a controllable parameter, when initializing JANUS. Just set verbose_out to True. It's False as default to preseve space. 

So, this change needs to be added to params_dict: 
```
params_dict = {

                .... everything prior.... 
                "verbose_out": True,
}
```


Regards
Akshat
